{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "proxmox-operator.serviceAccountName" . }}
  labels:
    {{- include "proxmox-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "proxmox-operator.serviceAccountName" . }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - proxmox.xfix.org
    resources:
      - '*'

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "proxmox-operator.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "proxmox-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "proxmox-operator.serviceAccountName" . }}
{{- end }}
